name: Pylint

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
        # pip install pylint
    - name: Analysing the code with pylint
      if: alwais()
      run: |
        pipenv install --dev pylint
        pipenv run pylint src
        pylint `ls -R|grep .py$|xargs`
    - name: Lint with flake8
      if: alwais()
      run: |
        pipenv run flake8 ./src
    - name: Test
      if: alwais()
      run: |
        pipenv run behave
